name: Deploy S3 Triggers

on:
  push:
    branches:
      - main

jobs:
  deploy-s3-triggers:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupération du code
      - name: 📥 Checkout du repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # 3️⃣ Configuration des identifiants AWS
      - name: 🔐 Configurer les identifiants AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.ACCESS_KEY_ID_CHEMS }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY_CHEMS }}
          aws-region:            eu-central-1

      # 4️⃣ Installation de Terraform
      - name: 🌍 Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # 5️⃣ Initialisation Terraform
      - name: Terraform Init
        run: terraform init

      # 6️⃣ Suppression des anciennes permissions Lambda (évite les conflits)
      - name: 🧹 Supprimer anciennes permissions Lambda
        run: |
          for lambda in hubspot-pdf-ocr-processor hubspot-llm-generate-json hubspot-create-deal; do
            if aws lambda get-policy --function-name $lambda > /dev/null 2>&1; then
              aws lambda get-policy --function-name $lambda \
                | jq -r '.Policy | fromjson.Statement[]?.Sid' \
                | grep AllowExecutionFromS3Bucket \
                | while read sid; do
                    echo "Suppression de $sid pour $lambda"
                    aws lambda remove-permission --function-name $lambda --statement-id $sid || true
                  done
            fi
          done

      # 7️⃣ Affichage du plan
      - name: Terraform Plan
        run: terraform plan

      # 8️⃣ Application auto du plan
      - name: Terraform Apply
        env:
          TF_LOG: INFO
        run: terraform apply -auto-approve
